#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0.2"]
# ///
"""Generate CATALOG.md from skill frontmatter.

Frontmatter is the single source of truth for what a skill is. The catalogue is
derived from it here, so that a skill cannot be described one way in its own
file and another way in the index people actually read.

``--check`` compares what would be generated against what is committed and
fails on any difference. CI runs it that way, which is what stops a hand-edit
from quietly becoming the version everyone reads.

There are deliberately no marketplace or plugin manifests. This repository is
not published yet -- it is shared as a git checkout while the skills mature,
and `install.sh` copies from that checkout. Publishing machinery written before
anyone has installed a skill is machinery nobody has tested.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Union

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import cli, log  # noqa: E402
from lib.discovery import LAYERS, Skill, discover, repo_root  # noqa: E402
from lib.frontmatter import FrontmatterError, parse_file  # noqa: E402

LOGGER = log.get_logger("build-catalog")

REPO_SLUG = "crv4all/agent-skills"
REPO_URL = f"https://github.com/{REPO_SLUG}"

OWNER_NAME = "CRV"
OWNER_URL = "https://www.crv4all.com"

GENERATED_BANNER = (
    "<!-- Generated by standards/scripts/build_catalog.py. Do not edit by hand: "
    "CI runs `build_catalog.py --check` and fails on drift. Change the skill "
    "frontmatter instead, then re-run with --write. -->"
)

LAYER_BLURB = {
    "utilities": "Cross-cutting tooling: the hard part is invoking something correctly.",
    "knowledge": "Reference and organizational context: facts a capable agent would otherwise get wrong.",
    "patterns": "Reusable implementation recipes, applied inside a larger task.",
    "processes": "End-to-end workflows with a reviewable deliverable.",
}

MATURITY_ORDER = {"stable": 0, "draft": 1, "deprecated": 2}


@dataclass(frozen=True)
class Entry:
    """One skill, flattened into everything the generated files need."""

    name: str
    layer: str
    description: str
    owner: str
    maturity: str
    execution: str
    model_tier: str
    version: Union[str, None]
    tags: list[str]
    review_cadence: Union[str, None]
    rel_path: str
    rel_skill_md: str

    @property
    def sort_key(self) -> tuple[int, int, str]:
        return (LAYERS.index(self.layer), MATURITY_ORDER.get(self.maturity, 3), self.name)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="build_catalog.py",
        description=(
            "Generate CATALOG.md from skill frontmatter. Writes a JSON summary to "
            "stdout; diagnostics go to stderr."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  uv run standards/scripts/build_catalog.py            # dry run: report drift\n"
            "  uv run standards/scripts/build_catalog.py --write    # write the files\n"
            "  uv run standards/scripts/build_catalog.py --check    # fail on drift (CI)\n"
            "  uv run standards/scripts/build_catalog.py --check --diff\n\n"
            "notes:\n"
            "  --check and --write are mutually exclusive: a check that repairs what it is\n"
            "  checking cannot fail, which makes it worthless in CI.\n\n"
            + cli.EXIT_CODE_HELP
        ),
    )
    parser.add_argument("--root", type=Path, default=None, help="Repository root (default: auto-detected).")
    parser.add_argument("--write", action="store_true", help="Write the generated files.")
    parser.add_argument("--check", action="store_true", help="Exit 1 if any generated file is out of date.")
    parser.add_argument("--diff", action="store_true", help="Print a unified diff to stderr for each drifted file.")
    parser.add_argument("--verbose", action="store_true", help="Verbose diagnostics on stderr.")
    parser.add_argument("--quiet", action="store_true", help="Only warnings and errors on stderr.")
    return parser


def load_entries(root: Path) -> tuple[list[Entry], list[str]]:
    skills, strays = discover(root)
    problems = [f"{stray.path.relative_to(root).as_posix()}: {stray.reason}" for stray in strays]
    entries: list[Entry] = []

    for skill in skills:
        try:
            parsed = parse_file(skill.skill_md)
        except FrontmatterError as exc:
            problems.append(str(exc))
            continue
        data = parsed.data
        metadata = data.get("metadata") if isinstance(data.get("metadata"), dict) else {}
        name = data.get("name")
        description = data.get("description")
        if not isinstance(name, str) or not isinstance(description, str):
            problems.append(f"{skill.rel_skill_md}: name and description must both be strings")
            continue
        tags_raw = metadata.get("tags")
        entries.append(
            Entry(
                name=name,
                layer=str(metadata.get("layer") or skill.layer),
                description=" ".join(description.split()),
                owner=str(metadata.get("owner") or "unassigned"),
                maturity=str(metadata.get("maturity") or "draft"),
                execution=str(metadata.get("execution") or "unspecified"),
                model_tier=str(metadata.get("model-tier") or "unspecified"),
                version=str(metadata["version"]) if metadata.get("version") else None,
                tags=[t for t in str(tags_raw).split(",") if t] if tags_raw else [],
                review_cadence=str(metadata["review-cadence"]) if metadata.get("review-cadence") else None,
                rel_path=skill.rel_path,
                rel_skill_md=skill.rel_skill_md,
            )
        )

    entries.sort(key=lambda entry: entry.sort_key)
    return entries, problems


def _first_sentence(description: str, limit: int = 160) -> str:
    """The catalogue table needs a summary, not the whole trigger clause."""
    for terminator in (". ", "! ", "? "):
        head, sep, _ = description.partition(terminator)
        if sep:
            candidate = head + terminator.strip()
            if len(candidate) <= limit:
                return candidate
    if len(description) <= limit:
        return description
    return description[: limit - 1].rsplit(" ", 1)[0] + "…"


def render_catalog(entries: list[Entry]) -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "# Skill catalogue",
        "",
        f"{len(entries)} skill(s) in [{REPO_SLUG}]({REPO_URL}).",
        "",
        "Install any of them with `install.sh`; see [docs/installing.md](docs/installing.md).",
        "",
        "Every skill runs in a subagent and states its model tier before starting. See",
        "[docs/design-principles.md](docs/design-principles.md) for the tier mapping.",
        "",
        "| Skill | Layer | Maturity | Runs as | Tier | Owner | Summary |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        lines.append(
            (
                "| [`{name}`]({path}/SKILL.md) | {layer} | {maturity} | {execution} | "
                "{tier} | {owner} | {summary} |"
            ).format(
                name=entry.name,
                path=entry.rel_path,
                layer=entry.layer,
                maturity=entry.maturity,
                execution=entry.execution,
                tier=entry.model_tier,
                owner=entry.owner,
                summary=_first_sentence(entry.description),
            )
        )

    lines.append("")
    for layer in LAYERS:
        in_layer = [entry for entry in entries if entry.layer == layer]
        lines.extend([f"## {layer}", "", LAYER_BLURB[layer], ""])
        if not in_layer:
            lines.extend(["_No skills in this layer yet._", ""])
            continue
        for entry in in_layer:
            lines.append(f"### [`{entry.name}`]({entry.rel_path}/SKILL.md)")
            lines.append("")
            lines.append(entry.description)
            lines.append("")
            details = [
                f"**Owner:** {entry.owner}",
                f"**Maturity:** {entry.maturity}",
                f"**Runs as:** {entry.execution}",
                f"**Model tier:** {entry.model_tier}",
            ]
            if entry.version:
                details.append(f"**Version:** {entry.version}")
            if entry.review_cadence:
                details.append(f"**Review:** {entry.review_cadence}")
            if entry.tags:
                details.append("**Tags:** " + ", ".join(f"`{tag}`" for tag in entry.tags))
            lines.append(" · ".join(details))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


GENERATED = {
    "CATALOG.md": render_catalog,
}


def main(argv: Union[list[str], None] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    log.configure(verbose=args.verbose, quiet=args.quiet)

    if args.write and args.check:
        LOGGER.error(
            "--write and --check are mutually exclusive: a check that repairs what it "
            "is checking can never fail"
        )
        return cli.EXIT_USAGE

    root = (args.root or repo_root()).resolve()
    entries, problems = load_entries(root)

    for problem in problems:
        LOGGER.error("%s", problem)
    if problems:
        LOGGER.error(
            "refusing to generate from a repository with unreadable skills; run "
            "validate_frontmatter.py first"
        )
        return cli.EXIT_MALFORMED

    results = []
    drifted = []
    for rel, render in GENERATED.items():
        target = root / rel
        expected = render(entries)
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        up_to_date = current == expected

        if not up_to_date:
            drifted.append(rel)
            if args.diff:
                diff = difflib.unified_diff(
                    (current or "").splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=f"{rel} (committed)",
                    tofile=f"{rel} (generated)",
                )
                sys.stderr.writelines(diff)

        if args.write and not up_to_date:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
            LOGGER.info("wrote %s", rel)

        results.append(
            {
                "path": rel,
                "existed": current is not None,
                "up_to_date": up_to_date,
                "action": "written" if (args.write and not up_to_date) else ("ok" if up_to_date else "drifted"),
            }
        )

    payload = {
        "tool": "build_catalog",
        "mode": "write" if args.write else ("check" if args.check else "report"),
        "root": str(root),
        "skills": [
            {
                "name": e.name,
                "layer": e.layer,
                "maturity": e.maturity,
                "execution": e.execution,
                "model_tier": e.model_tier,
                "path": e.rel_path,
            }
            for e in entries
        ],
        "files": results,
        "summary": {"generated": len(GENERATED), "drifted": 0 if args.write else len(drifted)},
    }
    cli.emit(payload)

    if args.write:
        LOGGER.info("%d skill(s) catalogued, %d file(s) up to date", len(entries), len(GENERATED))
        return cli.EXIT_OK

    if drifted:
        for rel in drifted:
            LOGGER.error("out of date: %s", rel)
        LOGGER.error("run `uv run standards/scripts/build_catalog.py --write` and commit the result")
        return cli.EXIT_FINDINGS if args.check else cli.EXIT_OK

    LOGGER.info("%d skill(s) catalogued, all generated files up to date", len(entries))
    return cli.EXIT_OK


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(cli.EXIT_INTERNAL)
